import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { type ReactNode } from "react";
import { cookieToInitialState } from "wagmi";

import { getConfig } from "../wagmi";
import { Providers } from "./providers";

import BackGroundImage from "../images/home-background.jpg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Wagmi",
  description: "Generated by create-wagmi",
};

export default function RootLayout(props: { children: ReactNode }) {
  const initialState = cookieToInitialState(
    getConfig(),
    headers().get("cookie")
  );
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          style={{
            backgroundImage: `url(${BackGroundImage.src})`,
            backgroundSize: "cover", // Ensures the background covers the entire page
            backgroundPosition: "center", // Centers the image
            backgroundRepeat: "no-repeat", // Avoids repeating the image
            backgroundAttachment: "fixed", // Keeps the image fixed while scrolling
            height: "100%", // Full viewport height
            width: "100%", // Full viewport width
            color: "white",
          }}
        >
          <Providers initialState={initialState}>{props.children}</Providers>
        </div>
      </body>
    </html>
  );
}
